# Generated by Django 5.0.1 on 2024-01-25 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_pizzeria_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzeria',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='(\\+212|0)([ \\-_/]*)(\\d[ \\-_/]*){9}\n')]),
        ),
    ]
